### PR TITLE
Working with g++ now.

### PR DESCRIPTION
**Pull request by danieagle**
test with "CC=g++ make all"
  OS: Linux Ubuntu Impish AMD64
  GCC/G++:  v11.2

### CODE REVIEW

**Comment by strlcat** [comment]
Thanks! I will review it more closely & commit by tomorrow.

**Review by strlcat — CHANGES_REQUESTED** [review]
Cannot accept header changes into support sources. Please remove.
mhexdump cast is ok, please keep it.
Thanks!

**Comment by danieagle** [comment]
> Cannot accept header changes into support sources. Please remove. mhexdump cast is ok, please keep it. Thanks!

Why sources ?
Why Changes ?

thanks,
Dani.

**Comment by strlcat** [comment]
after fixes applied, thanks.

**Pull request merged**
