### PR TITLE
Tf bit choose

### PR DESCRIPTION
**Pull request by danieagle**
Allow choose one #define TF_* in tfdef.h

it use a standard and simple copy operation disponible in all OS's.

And Very very thanks, for this lib.

Best Whishes,
Daniel.

### CODE REVIEW

**Comment by strlcat** [comment]
This change complicates things more than it solves. If you need to select endian/bit variant in your code, just change relevant defines with -D and #undef anything in tfdef.h.

**Comment by danieagle** [comment]
Hi!
This dont are so simple.

The installed headers need the value choosed. The -D option dont survave
beyond compilation.

What you prefer?
We need a mode to choose these value without manual edit and that choose be
installable.

We dont care How It Will be done 😃.

Best whishes,
Daniel.

Em dom, 19 de dez de 2021 20:50, Andrey Rys ***@***.***>
escreveu:

**Comment by strlcat** [comment]
This project has no install target other than in current CMakeLists.txt. You shall not implement it directly for this library, since this library is embeddable. Again, in your code when you import this library into it, edit tfdef.h freely to your taste. The library is just implementation which is not going to be used as shared system library. That's why this change is not appropriate for this repo.

**Comment by danieagle** [comment]
Hi! And thanks.

Well... I Will create a static lib in the same cmake makefile too.

Best whishes,
Daniel.


Em dom, 19 de dez de 2021 21:27, Andrey Rys ***@***.***>
escreveu:

**Pull request closed without merging**
